name: Foramina
author: Scott Treppa

main: st.fivepoints.foramina.Foramina
version: 1.0

depend: [Spout]

startup: postworld

commands:
   foramina:
      description: The plugins main command
      usage: /foramina 
